name: Run backend tests

on:
  push:
    branches: "**"
  pull_request:
    branches: [main]
  workflow_dispatch:
jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run tsc and npm run lint
        run: npm run validation
