name: Backend tests

on:
  push:
    branches: ["**"]
  workflow_dispatch:
jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: npm ci
      - name: Run tsc and npm run lint
        run: npm run validation
      - name: Run integration tests
        run: docker-compose -f docker-compose-test.yml up --abort-on-container-exit
